config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"

  resources :posts
  get "my_posts", to: "posts#my_posts"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :description

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/initial_page_controller.rb
class InitialPageController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :destroy ]

  def index
    @posts = Post.all
  end

  def my_posts
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.user_id = current_user.id

    if @post.save!
      redirect_to my_posts_path, notice: "Post saved successfully!"
    else
      redirect_to new_posts_path, alert: "Post save error!"
    end
  end

  def edit
  end

  def update
    if @post.update!(posts_params)
      redirect_to my_posts_path, notice: "Post edited successfully!"
    else
      redirect_to my_posts_path, alert: "Post edit error!"
    end
  end

  def destroy
    @post.destroy
    if @post.destroy
      redirect_to my_posts_path, notice: "Post deleted successfully!"
    else
      redirect_to my_posts_path, alert: "Post delete error!"
    end
  end

  def posts_params
    params.require(:post).permit(:title, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/initial_page_helper.rb
module InitialPageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog Ruby On Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbolinks-travk":"reload" %>
  </head>

  <body>

    <%= button_to "sign out", destroy_user_session_path, :method => :delete if user_signed_in? %>

    <div>
    <%= yield %>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form|%>
<%= form.text_field :title, value: post.title, placeholder:'Write your title:'%>

<br/>

<%= form.text_field :description, value: post.description, placeholder:'Write your post description:'%>

<br/>

<%= form.submit 'Send post'%>

<% end %>

app/views/posts/_post_template.html.erb
<div style="box-shadow: 0px 0px 10px rgba(10,10,100.3); padding: 20px;margin: 10px;">
    
    <h1><%= post.title %></h1>

    <hr/>

    <p><%= post.description %></p>

    <hr/>

    <small>Post written by:<%= post.user.email%></small>

    <% if post.user.id == current_user.id %>
    
    <hr/>

    <%= link_to "Edit post", edit_post_path(post) %>
    <%= button_to "Delete post", post, method: :delete %>
    <% end%>

    </div>

app/views/posts/edit.html.erb
<header>Welcome <%= current_user.email %> !</header>

<%= link_to 'Back to all posts', posts_path %>

<br/>

<h1>Edit Post</h1>

<br/>

<%= render partial: 'posts/form', locals: { post: @post} %>

app/views/posts/index.html.erb
<header>Welcome <%= current_user.email %> !</header>

<%= link_to 'My posts', my_posts_path %>

<%@posts.each do |post|%>
    <%= render partial: 'posts/post_template', locals: {post: post} %>  
<% end %>

app/views/posts/my_posts.html.erb
<header>Welcome <%= current_user.email %> !</header>

<%= link_to 'Back to all posts', posts_path %>

<br/>

<!--PT BR na linha abaixo deixei como new_post_path para seguir o padrão mas achei interessante anotar que  newposts/new também funciona
    EN in the line below I left it as new_post_path to follow the pattern but I thought it would be interesting to note that newposts/new also works
     -->
<%= link_to 'Create a new post', new_post_path  %>


<%@posts.each do |post|%>
    <%= render partial: 'posts/post_template', locals: {post: post} %>  
<% end %>

app/views/posts/new.html.erb
<%= link_to 'Back to all posts', posts_path %>

<br/>


<%= form_with model: @post do |form|%>
<%= form.text_field :title, placeholder:'Write your title:'%>

<br/>

<%= form.text_field :description, placeholder:'Write your post description:'%>

<br/>

<%= form.submit 'Send post'%>

<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>